app/urls.py
from django.conf.urls.defaults import *
from django.http import HttpResponse
from django.conf import settings
from django.contrib import admin
from django.contrib.auth.decorators import login_required
from django.views.decorators.cache import cache_page
from django.views.generic import TemplateView
from haystack.views import SearchView
from haystack.query import SearchQuerySet
from livechat.models import LiveChatResponse
from app.views import (CategoryDetailView, CategoryListView,
                        StoryCommentsView, ConfirmReportView,
                        ContactView,
                        ProfileView, VLiveEditProfile,
                        QuestionAnswerView, MyProfileView, MyProfileEdit,
                        PublicProfileView, UserCommentsView)
from app.forms import PasswordResetForm, PasswordResetEmailForm
from moderator.models import CommentReply
from app.models import Post
from django.contrib.comments import Comment
import object_tools

admin.autodiscover()
object_tools.autodiscover()

postsqs = SearchQuerySet().models(Post)
commentsqs = SearchQuerySet().models(Comment, CommentReply, LiveChatResponse)

def health(request):
    return HttpResponse('ok')


urlpatterns = patterns('',
    url(r'^health/$', health, name='health'),
    url(
        r'^$',
        TemplateView.as_view(template_name="app/home.html"),
        name='home'
    ),
    url(
        r'^about/$',
        TemplateView.as_view(template_name="app/about.html"),
        name='about'
    ),
    url(
        r'^faqs/$',
        TemplateView.as_view(template_name="app/faqs.html"),
        name='faqs'
    ),
    url(
        r'^contact/$',
        ContactView.as_view(),
        name='contact'
    ),
    url(
        r'^feedback/$',
        'app.views.sendfeedback',
        name='feedback'
    ),
    url(
        r'^help/$',
        TemplateView.as_view(template_name="app/help.html"),
        name='help'
    ),
    url(
        r'^login/$',
        'django.contrib.auth.views.login',
        {'template_name': 'app/login.html'},
        name='login'
    ),
    url(
        r'^logout/$',
        'app.views.logout',
        name='logout'
    ),
    url(
        r'^set_lang/$',
        'app.views.set_language',
        name='set_lang'
    ),
    url(
        r'^password-reset/$', 
        'django.contrib.auth.views.password_reset',
        {
            'password_reset_form': PasswordResetEmailForm,
            'template_name': 'app/password_reset_email.html',
        }, 
        name="reset_password_email"
    ),
    url(
        r'^password-reset-done/$',
        'django.contrib.auth.views.password_reset_done',
        {'template_name': 'app/password_reset_done.html'},
        name='password_reset_done'
    ),
    url(
        r'^reset/(?P<uidb36>[0-9A-Za-z]{1,13})-(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        'django.contrib.auth.views.password_reset_confirm',
        {'template_name': 'app/password_reset_confirm.html'},
        name='password_reset_confirm'
    ),
    url(
        r'^reset/done/$',
        'django.contrib.auth.views.password_reset_complete',
        {'template_name': 'app/password_reset_complete.html'},
        name='password_reset_complete'
    ),
    url(
        r'^poll-vote/(?P<poll_slug>[\w-]+)/$',
        'app.views.poll_vote',
        name='poll_vote'
    ),
    url(
        r'^post-comment/$',
        'app.views.post_comment',
        name='post_comment'
    ),
    (r'^comments/', include('django.contrib.comments.urls')),
    url(
        r'^terms/$',
        TemplateView.as_view(template_name="app/terms.html"),
        name='terms'
    ),
    url(
        r'^comment-terms/$',
        TemplateView.as_view(template_name="app/includes/comment_terms.html"),
        name='comment-terms'
    ),
    url(
        r'^content/(?P<category_slug>[\w-]+)/list/$',
        CategoryListView.as_view(),
        {},
        name='category_object_list'
    ),
    url(
        r'^content/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/$',
        CategoryDetailView.as_view(),
        {},
        name='category_object_detail'
    ),
    url(
        r'^content/(?P<category_slug>[\w-]+)/(?P<slug>[\w-]+)/comments/$',
        StoryCommentsView.as_view(),
        {},
        name='story_comments_list'
    ),
    url(r'^search/',  cache_page(SearchView(results_per_page=5,
                                            searchqueryset=postsqs), 60 * 60),
        name='haystack_search'),
    url(
        r'^accounts/register/$', 'registration.views.register',
        {'backend': 'app.registration_backend.MamaBackend'},
        name='registration_register'
    ),
    url(
        r'^accounts/register/done/',
        login_required(TemplateView.as_view(
            template_name="registration/done.html"
        )),
        name='registration_done'
    ),
    url(
        r'^view/myprofile/$',
        login_required(MyProfileView.as_view()),
        name='view_my_profile'
    ),
    url(
        r'^edit/myprofile/$',
        login_required(MyProfileEdit.as_view()),
        name='edit_my_profile'
    ),
    url(
        r'^accounts/profile/$',
        login_required(ProfileView.as_view()),
        name='profile'
    ),
    url(
        r'^public/profile/(?P<user_id>\d+)/$',
        PublicProfileView.as_view(),
        name='public_profile'
    ),
    url(
        r'^public/usercomments/(?P<user_id>\d+)/$',
        UserCommentsView.as_view(),
        name='public_user_comments'
    ),

    url(
        r'^comment-agree/$',
        "app.views.agree_comment",
        name='agree_comment'
    ),
    url(
        r'^report-comment/(?P<content_type>[\w-]+)/(?P<id>\d+)/(?P<vote>-?\d+)/$',
        'app.views.report_comment',
        name='report_comment'),
    url(
        r'^confirm-comment-report/(?P<content_type>[\w-]+)/(?P<id>\d+)/$',
        ConfirmReportView.as_view(),
        name='confirm_comment'),

    (r'^survey/', include('survey.urls', namespace='survey')),
    (r'^livechat/', include('livechat.urls', namespace='livechat')),
    (r'^admin/', include(admin.site.urls)),
    (r'^object-tools/', include(object_tools.tools.urls)),
    (r'^ckeditor/', include('ckeditor.urls')),
    url(r'^google-credentials/', include('google_credentials.urls')),
    url(r'^likes/like/(?P<content_type>[\w-]+)/(?P<id>\d+)/(?P<vote>-?\d+)$',
        'app.views.like',
        name='like'),
    url(r'^', include('jmbo.urls')),
    url(r'^djga/', include('google_analytics.urls')),
)

handler500 = 'app.views.server_error'

if settings.DEBUG:
    urlpatterns += patterns('',
        (r'^media/(?P<path>.*)$', 'django.views.static.serve',
         {'document_root': settings.MEDIA_ROOT}),
    )

project/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('app.urls')),
    # url(r'^grappelli/', include('grappelli.urls')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^i18n/', include('django.conf.urls.i18n')),
)

app/forms.py
import uuid
from datetime import date
import time
import ambient
from dateutil import parser
from django import forms
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.tokens import default_token_generator
from django.contrib.sites.models import get_current_site
from django.core.exceptions import ValidationError
from django.core.urlresolvers import reverse
from django.core.validators import RegexValidator
from django.forms.extras.widgets import SelectDateWidget
from django.utils.http import int_to_base36
from django.utils.safestring import mark_safe
from django.contrib.localflavor.ca.forms import CAPhoneNumberField
from django.core.mail import EmailMessage, mail_managers

from PIL import Image
from django.utils.translation import ugettext as _

from pml import forms as pml_forms
from registration.forms import RegistrationFormTermsOfService
from userprofile import utils
import app

from app.tasks import send_sms
from app.constants import (
    GENDER_CHOICES,
    IDENTITY_CHOICES,
)


class ContactForm(forms.Form):
    mobile_number = forms.CharField(max_length=64)
    message = forms.CharField(
        widget=forms.Textarea,
        label="Please use the field below to send us a message."
    )


class PasswordResetForm(PasswordResetForm):
    mobile_number = forms.CharField(max_length=64)

    def __init__(self, *args, **kwargs):
        super(PasswordResetForm, self).__init__(*args, **kwargs)
        del self.fields['email']

    def clean_mobile_number(self):
        """
        Validates that an active user exists with the given email address.
        """
        mobile_number = self.cleaned_data['mobile_number']
        # Fail with invalid number.
        try:
            self.profile = app.models.UserProfile.objects.get(
                mobile_number__exact=mobile_number
            )
            self.user = self.profile.user
        except app.models.UserProfile.DoesNotExist:
            raise forms.ValidationError(_("Unable to find an account for the "
                                        "provided mobile number. Please try "
                                        "again."))
        # Fail if user has already reset password today more than once.
        if self.profile.last_reset_date == date.today() \
                and self.profile.reset_count >= 2:
            raise forms.ValidationError(_("You have already tried to reset "
                                        "your PASSWORD today. Please wait "
                                        "for your SMS or try again tomorrow."))
        return mobile_number

    def save(self, *args, **kwargs):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """
        # Before we do anything else update reset counts for throttling.
        if self.profile.last_reset_date == date.today():
            self.profile.reset_count += 1
        else:
            self.profile.last_reset_date = date.today()
            self.profile.reset_count = 1
        self.profile.save()

        # Generate message containing url with users token.
        uid = int_to_base36(self.user.id)
        token = default_token_generator.make_token(self.profile.user)
        current_site = get_current_site(kwargs['request'])

        message = _(
            "Hi %(name)s. "
            "Follow this link to reset your PASSWORD: http://%(domain)s%(url)s") % {
            'name': self.user.username,
            'domain': current_site.domain,
            'url': reverse(
                'password_reset_confirm',
                kwargs={'uidb36': uid, 'token': token}
            )
        }

        send_sms.delay(self.profile.mobile_number, message)


class PasswordResetEmailForm(forms.Form):
    email = forms.EmailField()


    def clean_email(self):
        """
        Validates that an active user exists with the given email address.
        """
        email = self.cleaned_data['email']
        # Fail with invalid number.
        try:
            email = self.cleaned_data["email"]
            self.user = User.objects.get(email__iexact=email)
        except User.DoesNotExist:
            raise forms.ValidationError(_("Unable to find an account for the "
                                        "provided email. Please try "
                                        "again."))
        return email
    def save(self, *args, **kwargs):
        """
        Generates a one-use only link for resetting password and sends to the
        user.
        """

        uid = int_to_base36(self.user.id)
        token = default_token_generator.make_token(self.user)
        current_site = get_current_site(kwargs['request'])

        message = _(
            "Hi %(name)s. "
            "Follow this link to reset your PASSWORD: http://%(domain)s%(url)s") % {
            'name': self.user.username,
            'domain': current_site.domain,
            'url': reverse(
                'password_reset_confirm',
                kwargs={'uidb36': uid, 'token': token}
            )
        }

        subject = _("[A4W] Reset your PASSWORD")
        recipients = [self.user.email]
        from_address = settings.FROM_EMAIL_ADDRESS
        mail = EmailMessage(
            subject,
            message,
            from_address,
            recipients,
            headers={'From': from_address, 'Reply-To': from_address}
        )
        mail.send(fail_silently=True)


class RegistrationForm(RegistrationFormTermsOfService):
    mobile_number = CAPhoneNumberField(
        required=False,
        label=_("Your mobile number")
    )
    alias = forms.CharField(
       label=_("Display Name"),
       required=False
    )
    gender = forms.ChoiceField(
        label=_("Gender"),
        choices=GENDER_CHOICES,
        widget=forms.Select(),
        required=False)
    year_of_birth = forms.IntegerField(
        label=_("Year of birth"),
        required=False
    )
    identity = forms.ChoiceField(
        label=_("Identity"),
        choices=IDENTITY_CHOICES,
        widget=forms.Select(),
        required=False)

    def __init__(self, *args, **kwargs):
        super(RegistrationForm, self).__init__(*args, **kwargs)
        # set up the form
        #del self.fields['email']
        del self.fields['password2']
        self.fields.keyOrder = [
            'username',
            #'email',
            'password1',
            'mobile_number',
            'tos',
            'gender',
            'alias',
            'year_of_birth',
            'identity',
        ]
        self.fields['username'].label = _("Username")
        self.fields['email'].label = _("Email")
        self.fields['password1'].label = _("Password")

        self.fields['tos'].label = mark_safe('I accept the <a href="%s">terms '
                                             'and conditions</a> of use.'
                                             % reverse("terms"))

    def clean_mobile_number(self):
        mobile_number = self.cleaned_data['mobile_number']

        if not mobile_number:
            return

        try:
            self.profile=app.models.UserProfile.objects.get(
                mobile_number__exact=mobile_number
            )
            if self.profile.user.username == self.cleaned_data['username']:
                return mobile_number
            else:
                error_msg_1 = _('A user with that mobile number already exists.')
                error_msg_2 = _('Forgotten your PASSWORD?')
                raise ValidationError(error_msg_1 + ' <a href="%s">%s</a>' % (
                    reverse("reset_password_email"),
                    error_msg_2))
        except app.models.UserProfile.DoesNotExist:
            return mobile_number

    def clean_username(self):
        email = self.cleaned_data['username']
        RegexValidator('\w[\w\.-]*@\w[\w\.-]+\.\w+', message=_("Enter a valid email address."))(email)
        try:
            User.objects.get(
                email__exact=email
            )
            raise ValidationError(_('A user with that email already exists'))
        except User.DoesNotExist:
            return email

    def clean_gender(self):
        gender = self.cleaned_data['gender']
        return gender

    def clean_year_of_birth(self):
        year_of_birth = self.cleaned_data['year_of_birth']
        thisyear = time.localtime()[0]
        if year_of_birth > thisyear:
            raise ValidationError(u'Please enter a valid year')
        return year_of_birth

    def clean_identity(self):
        identity = self.cleaned_data['identity']
        return identity

class EditProfileForm(RegistrationForm):
    """
    The form to edit all options in the member's full profile.
    """
    about_me = forms.CharField(
        widget=forms.Textarea,
        required=False
    )

    avatar = forms.ImageField(
        label=_("Upload Picture"),
        required=False
    )

    username = forms.CharField(
        label=_("Email"),
        required=True
    )
    email = forms.CharField(
        max_length=100,
        label=_("Email"),
        widget=forms.HiddenInput()
    )
    first_name = forms.CharField(
        label=_("Name"),
        required=False
    )
    last_name = forms.CharField(
        max_length=100,
        label=_("Surname"),
        required=False
    )
    alias = forms.CharField(
       label=_("Display Name"),
       required=False
    )
    gender = forms.ChoiceField(
        label=_("Gender"),
        choices=GENDER_CHOICES,
        widget=forms.Select(),
        required=False)
    year_of_birth = forms.IntegerField(
        label=_("Year of birth"),
        required=False,
    )
    identity = forms.ChoiceField(
        label=_("Identity"),
        choices=IDENTITY_CHOICES,
        widget=forms.Select(),
        required=False)
    engage_anonymously = forms.BooleanField(
        label=_("Engage Anonymously"),

project/templates/app/mobi/base.html
<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
{% load cache afw_inclusion_tags %}
{% load i18n %}
<html xmlns="http://www.w3.org/1999/xhtml" class="js">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
    <title>{% trans "A4W Live" %}{% if object %} / {{ object.title }}{% endif %}</title>
    <meta name="viewport" content="width=device-width; initial-scale=1.0;" />
    <meta name="description" content="{% if object %}{{ object.description }}{% endif %}">
    <meta name="keywords" content="woman,women">
    <link rel="icon" href="{{ STATIC_URL }}img/a4wfavicon16.png" sizes="16x16">
    <link rel="icon" href="{{ STATIC_URL }}img/a4wfavicon32.png" sizes="32x32">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/style.min.css?v=20150804-2">
    <link rel="stylesheet" media="screen and (min-width: 20em)" href="{{ STATIC_URL }}css/enhanced.css?v=20150804-5">
    <link rel="stylesheet" href="{{ STATIC_URL }}css/googleExo2Font.css?">


    {% block extra_script %}
    {% endblock %}
</head>
<body>
    {% block nav %}
    <nav class="nav-main highlight-primary">
      <a href="/" id="logo" class="logo"><img src="{{ STATIC_URL }}img/a4w-live-20150521.png" srcset="{{ STATIC_URL }}img/a4w-live-20150521-2x.png 320w" sizes="100vw" alt="A4W Live"></a>
      <a href="#menu" id="jump"><i class="i i-hamburger"></i><span class="visuallyhidden">menu</span></a>
      <a href="#main" id="close" class="hidden"><i class="i i-close" aria-label="close"></i><span class="visuallyhidden">close</span></a>
      <a href="#main" id="back" class="hidden"><i class="i i-back" aria-label="back"></i><span class="visuallyhidden">back</span></a>
    </nav>
    {% endblock %}

    {% block following_header %}
    {% endblock %}

    <main id="main">

        {% block above_content %}
        {% endblock %}

        {% block messages %}
        {% if messages %}
            <br/><br/><br/>
            <form>
            <fieldset>
                {% for message in messages %}
                <p><strong>{{ message }}</strong></p>
                {% endfor %}
            </fieldset>
            </form>
        {% endif %}
        {% endblock %}

        {% block content %}
        {% endblock %}

        {% block footer %}
            {% block footer_search_form %}
            <form action="{% url haystack_search %}" class="form-search highlight-primary hidden" id="search">
              <fieldset>
                <legend>{% trans "Search" %}</legend>
                <label for="input-search"><span class="visuallyhidden">{% trans "Search:" %}</span>
                  <input type="search" id="input-search" name="q" placeholder="e.g. {% trans "women" %}" class="input-wide" />
                </label>
                <input type="submit" value='{% trans "Submit" %}' class="btn btn-wide" />
                <p><a href="javascript:fufu.hideSearchMenu();" id="search-cancel">Cancel</a></p>
              </fieldset>
            </form>
            {% endblock %}

            <div class="footer" role="contentinfo">
              <ul class="nav nav-social list-inline">
              <li><a href="https://www.facebook.com/A4WLive" target="_blank"><i class="i i-facebook"></i> <span class="visuallyhidden">Facebook</span></a></li><li><a href="https://twitter.com/A4WLive" target="_blank"><i class="i i-twitter"></i> <span class="visuallyhidden">Twitter</span></a></li>
            </ul>
              <ul class="nav nav-legal-lang list-inline" role="navigation">
              <li><a href="{% url about %}">{% trans "About" %}</a></li>
              <li><a href="{% url terms %}">{% trans "Terms" %}</a></li>
              <li><a href="{% url faqs %}">{% trans "Site FAQs" %}</a></li>
              <li><a href="{% url feedback %}">{% trans "Site Support" %}</a></li>
              <li>{% trans "Site Language:" %} <a href="{{english_url}}" {% if SITE_ID == 1 %}class="active"{%endif%}>English</a> <a href="{{french_url}}" {% if SITE_ID == 2 %}class="active"{%endif%}>Français</a></li>
            </ul>
              <div class="copyright">
              <p>&copy; {% now "Y" %} National Association of Friendship Centres.<br />{% trans "All rights reserved." %}</p>
            </div>
            </div>
        {% endblock %}

    </main>



    {% load google_analytics_tags %}
    <div style="display:none">
        <img src="{% google_analytics request %}" width="0" height="0" />
    </div>

    {% block menu_forms %}
    <form method="post" id="signin" action="{% url login %}" class="form-sign-in highlight-primary hidden">
      {% csrf_token %}
      <fieldset>
        <legend>{% trans "Sign in" %}</legend>
        <p>{% trans "Enter your Email and 4-digit password (numbers only)" %}</p>
        <label for="username">{% trans "Email" %}
          <input type="text" id="username" name="username" class="input-wide" />
        </label>
            <label for="pin">{% trans "PASSWORD" %}
          <input type="password" pattern="[0-9]{4}" id="pin" name="password" class="input-wide" />
        </label>
        <label for="remember-me">
          <input type="checkbox" id="remember-me" name="remember-me"/>
          {% trans "Remember me" %}
        </label>
        <input type="submit" value="{% trans "Submit" %}" class="btn btn-wide" />
      </fieldset>

      <a href="{% url reset_password_email %}">{% trans "I forgot my PASSWORD" %}</a>

      <div class="sign-up">
        <p>{% trans "Don't have an account?" %}<br />
        <a href="{% url registration_register %}">{% trans "Sign up here to get started" %}</a></p>
      </div>
    </form>

    <form method="post" id="register" action="{% url registration_register %}" class="form-register highlight-primary hidden">
      {% csrf_token %}
      <fieldset>
        <legend>{% trans "Register" %}</legend>

        <label for="username">{% trans "Email" %}
          <input type="text" id="username" name="username" class="input-wide" />
        </label>
<!--
        <label for="id_email">{% trans "Email" %}
        <input id="email" name="email" type="text" class="input-wide">
        </label> -->

        <label for="id_password1">{% trans "PASSWORD" %}
        <input name="password1" pattern="[0-9]{4}" id="id_password1" type="password" class="input-wide" maxlength="4">
        </label>

        <label for="mobile-number">{% trans "Mobile Number" %}
          <input type="tel" id="mobile-number" name="mobile_number" class="input-wide" />
        </label>
        <label for="display_name">{% trans "Display Name" %}
          <input type="text" id="display_name" name="alias" class="input-wide" />
        </label>
        <label for="id_gender">{% trans "Gender" %}
            <select name="gender" class="input-wide">
              <option value="">{% trans "Select Gender" %}</option>
              <option value="male">{% trans "Male" %} </option>
              <option value="female">{% trans "Female" %}</option>
              <option value="other">{% trans "Other" %}</option>
            </select>
        </label>

        <label for="id_year_of_birth">{% trans "Year of Birth" %}
        {% if form.year_of_birth.errors %}
          {% for error in form.year_of_birth.errors %}
              <p>{{ error }}.</p>
          {% endfor %}
        {% endif %}
        <input name="year_of_birth" id="id_year_of_birth" type="text" class="input-wide">
        </label>

        <label for="id_identity">{% trans "Identity" %}
        <select name="identity" class="input-wide">
          <option value="">{% trans "Select Identity" %}</option>
          <option value="first_nations_status">{% trans "First Nations Status" %}</option>
          <option value="first_nations_non_status">{% trans "First Nations Non-Status" %}</option>
          <option value="inuit">{% trans "Inuit" %}</option>
          <option value="metis">{% trans "Metis" %}</option>
          <option value="non_aboriginal">{% trans "Non-Aboriginal" %}</option>
        </select>
        </label>

        <label for="id_tos">
        <input id="id_tos" class="required" name="tos" type="checkbox"> {% trans "I accept the" %} <a href="/terms/">{% trans "terms and conditions" %}</a> {% trans "of use" %}.
        </label>
        <input type="submit" value="{% trans "Submit" %}" class="btn btn-wide btn-space" />
      </fieldset>
    </form>

    <form action="{% url haystack_search %}" class="form-search highlight-primary hidden" id="search">
    {% csrf_token %}

      <fieldset>
        <legend>{% trans "Search" %}</legend>

        <label for="input-search"><span class="visuallyhidden">{% trans "Search:" %}</span>
          <input type="search" id="input-search" name="q" placeholder="e.g. {% trans "women" %}" class="input-wide" />
        </label>
        <input type="submit" value="{% trans "Submit" %}" class="btn btn-wide" />
      </fieldset>
    </form>
    {% endblock %}

    {% block menu %}
    <nav class="nav-menu highlight-primary" id="menu">
      <ul class="nav list-block" role="navigation">
        {% if not user.is_authenticated %}
        <li><a href="{% url login %}" id="show-signin">{% trans "Sign in" %}</a></li>
        <li><a href="{% url registration_register %}" id="show-register">{% trans "Register" %}</a></li>
        {% else %}
        <li><a href="{% url view_my_profile %}">{% trans "View Profile" %}</a></li>
        <li><a href="{% url logout %}">{% trans "Logout" %}</a></li>
        {% endif %}
        <li><a href="{% url category_object_list 'stories' %}">{% trans "Stories" %}</a></li>
        <li><a href="{% url category_object_list 'celebrity' %}">{% trans "Celebrities" %}</a></li>
        <li><a href="{% url category_object_list 'fact' %}">{% trans "Facts" %}</a></li>
        <!--<li><a href="{% url category_object_list 'faq' %}">{% trans "FAQs" %}</a></li>-->
        <li><a href="{% url haystack_search %}" id="show-search">{% trans "Search" %}</a></li>
      </ul>
      {% if SITE_ID == 1 %}
      <p><a href="{{french_url}}" class="lang-change">FR</a></p>
      {% endif %}
      {% if SITE_ID == 2 %}
      <p><a href="{{english_url}}" class="lang-change">EN</a></p>
      {% endif %}
    </nav>
    <a href="#main" id="nav-close" class="hidden">main</a>
    {% endblock %}
    {% block nav_script %}
    <script type="text/javascript">
        /*! loadJS: load a JS file asynchronously. [c]2014 @scottjehl, Filament Group, Inc. (Based on http://goo.gl/REQGQ by Paul Irish). Licensed MIT */
      function loadJS( src, cb ){
        "use strict";
        var ref = window.document.getElementsByTagName( "script" )[ 0 ];
        var script = window.document.createElement( "script" );
        script.src = src;
        script.async = true;
        ref.parentNode.insertBefore( script, ref );
        if (cb && typeof(cb) === "function") {
          script.onload = cb;
        }
        return script;
      }

      // cut the mustard
      if('querySelector' in document && 'localStorage' in window && 'addEventListener' in window) {
        loadJS( "{{ STATIC_URL }}js/main.min.js?v=20150527" );
      }

    </script>
    {% endblock %}
    <script type="text/javascript">
      var _gaq = _gaq || [];
      _gaq.push(['_setAccount', 'UA-62895031-1']);
      _gaq.push(['_trackPageview']);

      (function() {
      var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
      ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
      var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
      })();
    </script>
</body>
</html>